services:
  postgres:
    image: postgres:18
    container_name: quran-map-postgres
    environment:
      POSTGRES_DB: quran_map
      POSTGRES_USER: quran
      POSTGRES_PASSWORD: quran
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: